FROM --platform=$TARGETPLATFORM  golang:1.14-buster

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get -y --no-install-recommends install zip unzip cmake vim pkg-config build-essential ca-certificates libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev

RUN go get -u -d gocv.io/x/gocv && \
    cd /go/src/gocv.io/x/gocv && \
    git checkout v0.24.0 && \
    sed -i "s/sudo //g" Makefile && \
    make download

RUN cd /go/src/gocv.io/x/gocv && \
    make build && \
    make sudo_install && \
    make clean && \
    make verify